### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by kostaa** [pulyaevskiy/firebase-functions-interop#35] opened 2018-10-21 12:37 UTC
Getting this error during the deployment. Not sure if this is a Firebase issue or the generated code is invalid. When I googled this found somewhat similar problems that were resolved by downgrading the Firebase tools versions. 

![image](https://user-images.githubusercontent.com/7585117/47266916-9f27c700-d534-11e8-9bd7-d3990c93ee0e.png)

These are two functions that I am deploying. However when I remove the 'applySystemPayeeRules' method and the dependency on the the library where this is implemented all is good. So this makes me think that maybe the generated code is not quite right.

![image](https://user-images.githubusercontent.com/7585117/47266969-6e945d00-d535-11e8-8e05-2bed0113a58b.png)

Here is the 'index.dart.js' if that helps. 
[index.dart.js.zip](https://github.com/pulyaevskiy/firebase-functions-interop/files/2499120/index.dart.js.zip)

**Comment by pulyaevskiy** [comment] 2018-10-21 22:40
Could you also provide following?

1. Dart SDK version (`dart --version`)
2. Node.js version (`node --version`)
2. Firebase tools version (`firebase --version`)
3. Contents of `package.json`
4. Contents of `pubspec.yaml`

This would help in investigating your issue.

**Comment by kostaa** [comment] 2018-10-22 04:28
Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "windows_x64"
Node version: v8.12.0
Firebase version: 5.1.1

```
package.json
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "firebase-admin": "^6.0.0",
    "firebase-functions": "^2.0.5"
  },
  "private": true,
  "main": "build/node/index.dart.js"
}
```

```
pubspec.yaml

name: mv_cloud_functions
version: 1.0.0

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  firebase_functions_interop: ^1.0.0-dev
  system_payee_rules:
    path: ../lib_sys_payee_rules

dev_dependencies:
  build_node_compilers: any
  build_runner: any
  test: any
```
These are the actual versions 

firebase_functions_interop: "1.0.0-dev.10.0"
build_node_compilers: "0.2.0"
build_runner: "1.0.0"

**Comment by kostaa** [comment] 2018-10-27 12:15
Hi @pulyaevskiy, have you had time to have a look into this?

**Comment by pulyaevskiy** [comment] 2018-10-27 21:02
Hey, it's a bit hard to reproduce this error on my end giving available information.

I suspect that there is some code in `lib_sys_payee_rules` which causes this issue. If there is any way you can compose a reduced test case, this would help significantly.

**Comment by kostaa** [comment] 2018-10-28 09:31
The `lib_sys_payee_rules` library has dependencies on some other libraries (eg `quiver`) and I am currently writing another cloud function that will need `dart:convert` library and maybe some others. 

In your examples you seem to use only the underlying Firestore javascript libraries. I am trying to be careful when bringing in additional dependencies but it would be good to know the limitations - what is allowed and what is not.

**Comment by pulyaevskiy** [comment] 2018-10-28 18:19
In general, with JS interop you can't use `dart:io` or any package which depends on `dart:io` because this library is only available in the Dart VM. That's the main limitation.

For this reason I've also created `node_interop` and [node_io](https://pub.dartlang.org/packages/node_io) packages. Nice thing about `node_io` is that it wraps Node.js I/O using the same interfaces you normally use in `dart:io`, so you get Futures and Streams for free. Note though that I've only implemented a portion of  `dart:io` interfaces (most FS classes, HttpServer), so if you end up needing a method which throws `UnimplementedError` feel free to submit an issue here: https://github.com/pulyaevskiy/node-interop/issues.

If you need to make an HTTP request I'd also recommend [node_http](https://pub.dartlang.org/packages/node_http) which implements HttpClient interface from [http](https://pub.dartlang.org/packages/http) package.

Other built-in libraries like `dart:convert` can be used without any issues.

**Comment by kostaa** [comment] 2018-10-28 18:50
Great that is good news. I will try and narrow it down to the piece of code that is causing the issue.

**Comment by kostaa** [comment] 2018-11-01 06:34
Managed to find the issue. One of the libraries that I was bringing in contains a class that imports the `dart:io` library. All works as expected once I removed this class from the library. 

However this class is not used by any of the classes reachable from the cloud functions I am deploying. Since is not reachable I would expect that it is not included in the compiled JavaScript code.

**Comment by pulyaevskiy** [comment] 2018-11-01 17:01
Great you resolved this!

> Since is not reachable I would expect that it is not included in the compiled JavaScript code.

I would expect the same. Is it an open source library from Pub? Would be nice to understand why it causes issues.

**Comment by kostaa** [comment] 2018-11-02 05:33
No these are all my libraries. I will try an reproduce this in a small project.

**Comment by pulyaevskiy** [comment] 2018-11-02 17:01
Ok, no worries. I'll close this for now, but feel free to send updates if you find something interesting.

**Closed by pulyaevskiy** 2018-11-02 17:01 UTC

**Comment by kostaa** [comment] 2018-11-07 19:51
Just to let you know that I have not managed to reproduce this. Looks like I had my wires crossed somewhere in the original implementation.

**Comment by pulyaevskiy** [comment] 2018-11-07 19:58
Good to know, thanks for getting back on this.
